base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path('registerUser/', views.registerUser, name='register'),
    path('userCreated/', views.userCreated, name="userCreated"),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('', views.index, name="index"),
    path('unauthorised/', views.unauthorisedUser, name="unauthorised"),
    path('about/', views.aboutUs, name='about'),
    path('addTestimonial/', views.TestimonialCreateView.as_view(), name='addTestimonial'),
    
    # Urls for student's views are below this
    path('studentPage', views.studentPage, name="studentPage"),
    path('postStudent', views.StudentCreateView.as_view(), name="postStudent"),
    path('viewTeachers', views.viewTeacher, name="viewTeacher"),
    path('confirmEnrolment', views.enrol, name="confirmEnrolment"),
    path('notStudent/', views.notStudent, name="notStudent"),
    path('subjects/', views.viewSubjects, name="subjects"),
    path('subjects/viewSubjectTeachers/<int:id>/', views.viewSubjectTeachers, name='viewSubjectTeachers'),
    path('wrongTeacher/', views.wrongTeacher, name='wrongTeacher'),
    
    # Urls for teacher's views are below this
    path('teacherPage', views.teacherPage, name="teacherPage"),
    path('postTeacher/', views.TeacherCreateView.as_view(), name="postTeacher"),
    path('teacherDetail/<pk>', views.TeacherDetailView.as_view(), name="teacherDetail"),
    path('teacherProfile/<pk>', views.teacherProfile, name="teacherProfile"),
    path('notTeacher/', views.notTeacher, name="notTeacher"),
]

holiday_study/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
# import jsonfield
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Subject(models.Model):
  subjectName = models.CharField(max_length=256)
  subjectImage = models.ImageField(upload_to="photos/%y/%m/%d", blank=True)
  
  def __str__(self):
    return self.subjectName
  
class CurrentClass(models.Model):
  className = models.CharField(max_length=256)
  
  def __str__(self):
    return self.className
  
class Student(models.Model):
  studentName = models.ForeignKey(User, on_delete=models.CASCADE)
  currentSchool = models.CharField(max_length=500)
  subjects = models.ManyToManyField(Subject, through='StudentSubject')
  currentClass = models.ForeignKey(CurrentClass, on_delete=models.CASCADE)
  studentImage = models.ImageField(upload_to="photos/%y/%m/%d", blank=True)
  
  def __str__(self):
    return self.studentName.last_name
  
class Teacher(models.Model):
  teacherName = models.ForeignKey(User, on_delete=models.CASCADE)
  subjects = models.ManyToManyField(Subject, through='TeacherSubject')
  students = models.ManyToManyField(Student, through='TeacherEnrolment')
  currentSchool = models.CharField(max_length=400)
  teacherImage = models.ImageField(upload_to="photos/%y/%m/%d", blank=True)
  teacherDescription = models.TextField()
  teacherFee = models.IntegerField()
  
  def __str__(self):
    return self.teacherName.last_name
  
class TeacherSubject(models.Model):
  teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
  subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
  
class StudentSubject(models.Model):
  student = models.ForeignKey(Student, on_delete=models.CASCADE)
  subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
  
class TeacherEnrolment(models.Model):
  teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
  student = models.ForeignKey(Student, on_delete=models.CASCADE)
  subjects = models.ManyToManyField(Subject, through="TeacherEnrolmentSubject")
  
  class Meta:
    unique_together = [['teacher', 'student']]
    
class TeacherEnrolmentSubject(models.Model):
  teacherEnrolment = models.ForeignKey(TeacherEnrolment, on_delete=models.CASCADE)
  subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    
class Testimonial(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  message = models.TextField()
  role = models.CharField(max_length=256)
  
  def __str__(self):
    return self.author.username

base/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import TeacherEnrolment

class SignUpForm(UserCreationForm):
  class Meta:
    model = User
    fields = ['first_name', 'last_name', 'username', 'email']

base/views.py
# import json
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

from .forms import SignUpForm
from . models import Teacher, Student, Subject, StudentSubject, TeacherEnrolment, TeacherSubject, Testimonial

# Create your views here.

def registerUser(request):
  form = SignUpForm()
  
  if request.method == 'POST':
    form = SignUpForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('base:index')
    else:
      messages.error(request, "Form Error:(")
      return redirect('base:register')
  
  context = {
    'form': form
  }
  return render(request, "base/create_user.html", context)

def userCreated(request):
  
  return render(request, "base/user_created_success.html")

def unauthorisedUser(request):
  
  return render(request, 'base/unauthorised_user.html')
  
def loginUser(request):
  
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']
    
    user = authenticate(request, username=username, password=password)
    
    if user is not None:
      login(request, user)
      return redirect('base:index')
    else:
      messages.error("The login details do not match.")
      return redirect('base:login')
    
  return render(request, 'base/login_user.html')
  
   
def logoutUser(request):
  logout(request)
  
  return redirect('base:index')

def index(request):
  navbar = 'index'
  teachers = Teacher.objects.all()
  subjects = Subject.objects.all()
  testimonials = Testimonial.objects.all()
  
  context = {
    'navbar': navbar,
    'teachers': teachers,
    'subjects': subjects,
    'testimonials': testimonials,
  }
  return render(request, 'base/home.html', context)

def aboutUs(request):
  navbar = 'about'
  
  context = {
    'navbar': navbar,
  }
  return render(request, 'base/about.html', context)

class TestimonialCreateView(CreateView):
  model = Testimonial
  fields = ['message']
  template_name = 'base/testimonial_create.html'
  
  def form_valid(self, form):
    teacher = Teacher.objects.filter(teacherName=self.request.user.id)
    student = Student.objects.filter(studentName=self.request.user.id)

    if teacher:
      role = 'teacher'
    elif student:
      role = 'student'
    else:
      role = 'user'

    form.instance.author = self.request.user
    form.instance.role = role
    return super().form_valid(form)
  
  success_url = reverse_lazy('base:index')

# Student views are below here
def studentPage(request):
  navbar = 'students'
  # Check whether student is registered
  isRegistered = Student.objects.filter(studentName=request.user.id)
  
  isTeacher = Teacher.objects.filter(teacherName=request.user.id)
  if isTeacher:
    return redirect('base:notStudent')
  else:
    students = Student.objects.all()
    
    context = {
      'students': students,
      'isRegistered': isRegistered,
      'navbar': navbar,
    }
    return render(request, 'base/student_page.html', context)

class StudentCreateView(CreateView):
  model = Student
  fields = ['currentSchool', 'subjects', 'currentClass', 'studentImage']
  template_name = 'base/create_student.html'
  
  def form_valid(self, form):
    form.instance.studentName = self.request.user
    return super().form_valid(form)
  
  success_url = reverse_lazy('base:studentPage')
  
def viewSubjectTeachers(request, id):
  subject = Subject.objects.get(pk=id)
  teachers = TeacherSubject.objects.filter(subject=id)
  
  context = {
    'teachers': teachers,
    'subject': subject
  }
  return render(request, 'base/view_subject_teachers.html', context)

def viewSubjects(request):
  navbar = 'subjects'
  subjects = Subject.objects.all()
  
  context = {
    'subjects': subjects,
    'navbar': navbar,
  }
  return render(request, 'base/subjects_page.html', context)

# Teacher views are from this point onwards
def teacherPage(request):
  navbar = "viewTeacher"
  isRegistered = Teacher.objects.filter(teacherName=request.user.id)
  isStudent = Student.objects.filter(studentName=request.user.id)

  # The code belo was supposed to restrict a student from accessing the teacher page
  # if isStudent:
  #   return redirect('base:notTeacher')
  
  teachers = Teacher.objects.all()
  
  context = {
    'teachers': teachers,
    'isRegistered': isRegistered,
    'isStudent': isStudent,
    'navbar': navbar,
  }
  return render(request, 'base/teacher_page.html', context)

class TeacherCreateView(CreateView):
  model = Teacher
  fields = ['subjects', 'currentSchool', 'teacherFee', 'teacherImage']
  template_name = 'base/create_teacher.html'
  
  def form_valid(self, form):
    form.instance.teacherName = self.request.user
    return super().form_valid(form)
    
  
  success_url = reverse_lazy('base:teacherPage')
  
class TeacherDetailView(DetailView):
  model = Teacher
  context_object_name = 'teacher'
  template_name = 'base/teacher_detail.html'
  
def teacherProfile(request, pk):
  teacher = Teacher.objects.get(pk=pk)
  students = TeacherEnrolment.objects.filter(teacher=teacher.id)
  
  context = {
    'teacher': teacher, 
    'students': students,
  }
  return render(request, 'base/teacher_profile.html', context)
  
def viewTeacher(request):
  navbar = 'viewTeacher'
  teachers = Teacher.objects.all()
  
  context = {
    'teachers': teachers,
    'navbar': navbar,
  }
  return render(request, 'base/view_teachers.html', context)

@login_required(login_url='base:login')
def enrol(request): 
  # Getting logged teacher
  teacherId = request.GET['teacherId']
  
  # Getting the student enroling
  currentUser = request.user
  student = Student.objects.get(studentName=currentUser.id)
  
  # Checking whether current user is actually a student.
  if student:
    teacher = Teacher.objects.get(id=teacherId)
    studentSubjects = student.subjects.all()
    teacherSubjects = teacher.subjects.all()
    
    # Varible to confirm whether a teacher teaches a particular subject
    teaches = False
    
    for teacherSubject in teacherSubjects:
      for studentSubject in studentSubjects:
        if studentSubject == teacherSubject:
          teaches = True
          break
      else:
        continue
      break
      
    if teaches:
      if request.method == 'POST':
        teacherId = request.POST['teacherId']
        subjects = request.POST.getlist('checks[]')
        student = Student.objects.get(studentName=currentUser.id)
        enrolment = TeacherEnrolment.objects.create(teacher=teacher, student=student)
        enrolment.save()
        
        # saving the subjects enrolled for by a student
        for subject in subjects:
          enrolment.subjects.add(*Subject.objects.filter(id=subject))
        
        return redirect('base:viewTeacher')
    else:
      return redirect('base:wrongTeacher')
  else:
    return redirect('base:unauthorised')
  
  teacher = Teacher.objects.get(id=teacherId)

  context = {
    'teacher': teacher,
    'student': student,
  }
  
  return render(request, 'base/confirm_enrolment.html', context)

def wrongTeacher(request):
  
  return render(request, 'base/wrong_teacher.html')

def notStudent(request):
  
  return render(request, 'base/not_student.html')

def notTeacher(request):
  
  return render(request, 'base/not_teacher.html')

base/templates/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>HolidayStudy</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a href="index.html" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>HolidayStudy</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="{% url 'base:index' %}" class="nav-item nav-link 
                {% if navbar == 'index' %}active{% endif %}
                ">Home</a>
                <a href="{% url 'base:about' %}" class="nav-item nav-link
                {% if navbar == 'about' %}active{% endif %}
                ">About</a>
                <a href="{% url 'base:teacherPage' %}" class="nav-item nav-link
                {% if navbar == 'viewTeacher' %}active{% endif %}
                ">Teachers</a>
                <a href="{% url 'base:subjects' %}" class="nav-item nav-link
                {% if navbar == 'subjects' %}active{% endif %}
                ">Subjectss</a>
                <a href="{% url 'base:studentPage' %}" class="nav-item nav-link
                {% if navbar == 'students' %}active{% endif %}
                ">Students</a>
            </div>
            {% if request.user.is_authenticated %}
            <a href="{% url 'base:logout' %}" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Logout</a>
            {% else %}
            <a href="{% url 'base:login' %}" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Login</a>
            {% endif %}
        </div>
    </nav>
    <!-- Navbar End -->
  {% block content %} {% endblock %}
<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
  <div class="container py-5">
      <div class="row g-5">
          <div class="col-lg-3 col-md-6">
              <h4 class="text-white mb-3">Quick Link</h4>
              <a class="btn btn-link" href="">About Us</a>
              <a class="btn btn-link" href="">Contact Us</a>
              <a class="btn btn-link" href="">Privacy Policy</a>
              <a class="btn btn-link" href="">Terms & Condition</a>
              <a class="btn btn-link" href="">FAQs & Help</a>
          </div>
          <div class="col-lg-3 col-md-6">
              <h4 class="text-white mb-3">Contact</h4>
              <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Makerere, Kampala, Uganda</p>
              <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+256 751718886</p>
              <p class="mb-2"><i class="fa fa-envelope me-3"></i>holidaystudy@gmail.com</p>
              <div class="d-flex pt-2">
                  <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                  <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                  <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                  <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
              </div>
          </div>
          {% comment %} <div class="col-lg-3 col-md-6">
              <h4 class="text-white mb-3">Newsletter</h4>
              <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
              <div class="position-relative mx-auto" style="max-width: 400px;">
                  <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                  <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
              </div>
          </div> {% endcomment %}
      </div>
  </div>
  <div class="container">
      <div class="copyright">
          <div class="row">
              <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                  &copy; <a class="border-bottom" href="#">HolidayStudy</a>, All Right Reserved.

                  <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                  Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a><br><br>
                  Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
              </div>
              <div class="col-md-6 text-center text-md-end">
                  <div class="footer-menu">
                      <a href="">Home</a>
                      {% comment %} <a href="">Cookies</a> {% endcomment %}
                      <a href="">Help</a>
                      {% comment %} <a href="">FAQs</a> {% endcomment %}
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>