base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path('registerUser/', views.registerUser, name='register'),
    path('userCreated/', views.userCreated, name="userCreated"),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('', views.index, name="index"),
    path('unauthorised/', views.unauthorisedUser, name="unauthorised"),
    path('about/', views.aboutUs, name='about'),
    path('addTestimonial/', views.TestimonialCreateView.as_view(), name='addTestimonial'),
    
    # Urls for student's views are below this
    path('studentPage', views.studentPage, name="studentPage"),
    path('postStudent', views.StudentCreateView.as_view(), name="postStudent"),
    path('viewTeachers', views.viewTeacher, name="viewTeacher"),
    path('confirmEnrolment', views.enrol, name="confirmEnrolment"),
    path('notStudent/', views.notStudent, name="notStudent"),
    path('subjects/', views.viewSubjects, name="subjects"),
    path('subjects/viewSubjectTeachers/<int:id>/', views.viewSubjectTeachers, name='viewSubjectTeachers'),
    path('wrongTeacher/', views.wrongTeacher, name='wrongTeacher'),
    
    # Urls for teacher's views are below this
    path('teacherPage', views.teacherPage, name="teacherPage"),
    path('postTeacher/', views.TeacherCreateView.as_view(), name="postTeacher"),
    path('teacherDetail/<pk>', views.TeacherDetailView.as_view(), name="teacherDetail"),
    path('teacherProfile/<pk>', views.teacherProfile, name="teacherProfile"),
    path('notTeacher/', views.notTeacher, name="notTeacher"),
]

holiday_study/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
# import jsonfield
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Subject(models.Model):
  subjectName = models.CharField(max_length=256)
  subjectImage = models.ImageField(upload_to="photos/%y/%m/%d", blank=True)
  
  def __str__(self):
    return self.subjectName
  
class CurrentClass(models.Model):
  className = models.CharField(max_length=256)
  
  def __str__(self):
    return self.className
  
class Student(models.Model):
  studentName = models.ForeignKey(User, on_delete=models.CASCADE)
  currentSchool = models.CharField(max_length=500)
  subjects = models.ManyToManyField(Subject, through='StudentSubject')
  currentClass = models.ForeignKey(CurrentClass, on_delete=models.CASCADE)
  studentImage = models.ImageField(upload_to="photos/%y/%m/%d", blank=True)
  
  def __str__(self):
    return self.studentName.last_name
  
class Teacher(models.Model):
  teacherName = models.ForeignKey(User, on_delete=models.CASCADE)
  subjects = models.ManyToManyField(Subject, through='TeacherSubject')
  students = models.ManyToManyField(Student, through='TeacherEnrolment')
  currentSchool = models.CharField(max_length=400)
  teacherImage = models.ImageField(upload_to="photos/%y/%m/%d", blank=True)
  teacherDescription = models.TextField()
  teacherFee = models.IntegerField()
  
  def __str__(self):
    return self.teacherName.last_name
  
class TeacherSubject(models.Model):
  teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
  subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
  
class StudentSubject(models.Model):
  student = models.ForeignKey(Student, on_delete=models.CASCADE)
  subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
  
class TeacherEnrolment(models.Model):
  teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
  student = models.ForeignKey(Student, on_delete=models.CASCADE)
  subjects = models.ManyToManyField(Subject, through="TeacherEnrolmentSubject")
  
  class Meta:
    unique_together = [['teacher', 'student']]
    
class TeacherEnrolmentSubject(models.Model):
  teacherEnrolment = models.ForeignKey(TeacherEnrolment, on_delete=models.CASCADE)
  subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    
class Testimonial(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  message = models.TextField()
  role = models.CharField(max_length=256)
  
  def __str__(self):
    return self.author.username

base/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import TeacherEnrolment

class SignUpForm(UserCreationForm):
  class Meta:
    model = User
    fields = ['first_name', 'last_name', 'username', 'email']

base/views.py
# import json
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

from .forms import SignUpForm
from . models import Teacher, Student, Subject, StudentSubject, TeacherEnrolment, TeacherSubject, Testimonial

# Create your views here.

def registerUser(request):
  form = SignUpForm()
  
  if request.method == 'POST':
    form = SignUpForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('base:index')
    else:
      messages.error(request, "Form Error:(")
      return redirect('base:register')
  
  context = {
    'form': form
  }
  return render(request, "base/create_user.html", context)

def userCreated(request):
  
  return render(request, "base/user_created_success.html")

def unauthorisedUser(request):
  
  return render(request, 'base/unauthorised_user.html')
  
def loginUser(request):
  
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']
    
    user = authenticate(request, username=username, password=password)
    
    if user is not None:
      login(request, user)
      return redirect('base:index')
    else:
      messages.error("The login details do not match.")
      return redirect('base:login')
    
  return render(request, 'base/login_user.html')
  
   
def logoutUser(request):
  logout(request)
  
  return redirect('base:index')

def index(request):
  navbar = 'index'
  teachers = Teacher.objects.all()
  subjects = Subject.objects.all()
  testimonials = Testimonial.objects.all()
  
  context = {
    'navbar': navbar,
    'teachers': teachers,
    'subjects': subjects,
    'testimonials': testimonials,
  }
  return render(request, 'base/home.html', context)

def aboutUs(request):
  navbar = 'about'
  
  context = {
    'navbar': navbar,
  }
  return render(request, 'base/about.html', context)

class TestimonialCreateView(CreateView):
  model = Testimonial
  fields = ['message']
  template_name = 'base/testimonial_create.html'
  
  def form_valid(self, form):
    teacher = Teacher.objects.filter(teacherName=self.request.user.id)
    student = Student.objects.filter(studentName=self.request.user.id)

    if teacher:
      role = 'teacher'
    elif student:
      role = 'student'
    else:
      role = 'user'

    form.instance.author = self.request.user
    form.instance.role = role
    return super().form_valid(form)
  
  success_url = reverse_lazy('base:index')

# Student views are below here
def studentPage(request):
  navbar = 'students'
  # Check whether student is registered
  isRegistered = Student.objects.filter(studentName=request.user.id)
  
  isTeacher = Teacher.objects.filter(teacherName=request.user.id)
  if isTeacher:
    return redirect('base:notStudent')
  else:
    students = Student.objects.all()
    
    context = {
      'students': students,
      'isRegistered': isRegistered,
      'navbar': navbar,
    }
    return render(request, 'base/student_page.html', context)

class StudentCreateView(CreateView):
  model = Student
  fields = ['currentSchool', 'subjects', 'currentClass', 'studentImage']
  template_name = 'base/create_student.html'
  
  def form_valid(self, form):
    form.instance.studentName = self.request.user
    return super().form_valid(form)
  
  success_url = reverse_lazy('base:studentPage')
  
def viewSubjectTeachers(request, id):
  subject = Subject.objects.get(pk=id)
  teachers = TeacherSubject.objects.filter(subject=id)
  
  context = {
    'teachers': teachers,
    'subject': subject
  }
  return render(request, 'base/view_subject_teachers.html', context)

def viewSubjects(request):
  navbar = 'subjects'
  subjects = Subject.objects.all()
  
  context = {
    'subjects': subjects,
    'navbar': navbar,
  }
  return render(request, 'base/subjects_page.html', context)

# Teacher views are from this point onwards
def teacherPage(request):
  navbar = "viewTeacher"
  isRegistered = Teacher.objects.filter(teacherName=request.user.id)
  isStudent = Student.objects.filter(studentName=request.user.id)

  # The code belo was supposed to restrict a student from accessing the teacher page
  # if isStudent:
  #   return redirect('base:notTeacher')
  
  teachers = Teacher.objects.all()
  
  context = {
    'teachers': teachers,
    'isRegistered': isRegistered,
    'isStudent': isStudent,
    'navbar': navbar,
  }
  return render(request, 'base/teacher_page.html', context)

class TeacherCreateView(CreateView):
  model = Teacher
  fields = ['subjects', 'currentSchool', 'teacherFee', 'teacherImage']
  template_name = 'base/create_teacher.html'
  
  def form_valid(self, form):
    form.instance.teacherName = self.request.user
    return super().form_valid(form)
    
  
  success_url = reverse_lazy('base:teacherPage')
  
class TeacherDetailView(DetailView):
  model = Teacher
  context_object_name = 'teacher'
  template_name = 'base/teacher_detail.html'
  
def teacherProfile(request, pk):
  teacher = Teacher.objects.get(pk=pk)
  students = TeacherEnrolment.objects.filter(teacher=teacher.id)
  
  context = {
    'teacher': teacher, 
    'students': students,
  }
  return render(request, 'base/teacher_profile.html', context)
  
def viewTeacher(request):
  navbar = 'viewTeacher'
  teachers = Teacher.objects.all()
  
  context = {
    'teachers': teachers,
    'navbar': navbar,
  }
  return render(request, 'base/view_teachers.html', context)

@login_required(login_url='base:login')
def enrol(request): 
  # Getting logged teacher
  teacherId = request.GET['teacherId']
  
  # Getting the student enroling
  currentUser = request.user
  student = Student.objects.get(studentName=currentUser.id)
  
  # Checking whether current user is actually a student.
  if student:
    teacher = Teacher.objects.get(id=teacherId)
    studentSubjects = student.subjects.all()
    teacherSubjects = teacher.subjects.all()
    
    # Varible to confirm whether a teacher teaches a particular subject
    teaches = False
    
    for teacherSubject in teacherSubjects:
      for studentSubject in studentSubjects:
        if studentSubject == teacherSubject:
          teaches = True
          break
      else:
        continue
      break
      
    if teaches:
      if request.method == 'POST':
        teacherId = request.POST['teacherId']
        subjects = request.POST.getlist('checks[]')
        student = Student.objects.get(studentName=currentUser.id)
        enrolment = TeacherEnrolment.objects.create(teacher=teacher, student=student)
        enrolment.save()
        
        # saving the subjects enrolled for by a student
        for subject in subjects:
          enrolment.subjects.add(*Subject.objects.filter(id=subject))
        
        return redirect('base:viewTeacher')
    else:
      return redirect('base:wrongTeacher')
  else:
    return redirect('base:unauthorised')
  
  teacher = Teacher.objects.get(id=teacherId)

  context = {
    'teacher': teacher,
    'student': student,
  }
  
  return render(request, 'base/confirm_enrolment.html', context)

def wrongTeacher(request):
  
  return render(request, 'base/wrong_teacher.html')

def notStudent(request):
  
  return render(request, 'base/not_student.html')

def notTeacher(request):
  
  return render(request, 'base/not_teacher.html')

base/templates/base/about.html
{% extends 'base_template.html' %}
{% block content %}
<div class="container" style="height: 80vh">
  <h1>About Page</h1>

</div>
{% endblock %}

base/templates/base/create_student.html
{% extends 'base_template.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container m-3 p-3 mx-auto w-50" style="border: 1px solid #ccc;">
<h1>Register as Student</h1>
<p><h4>Name : {{ user.last_name }} {{ user.first_name }}</h4></p>
<p><h4>Email : {{ user.email }}</h4></p>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Upload">
</form>
</div>
{% endblock %}

base/templates/base/create_user.html
{% extends 'base_template.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container m-3 p-4 mx-auto w-50 text-justify" style="border: 1px solid #ccc;">
<h1>Register user</h1>
<form action="" method="post" class="mw-80">
  {% csrf_token %}
  <div class="fieldWrapper">
    {{ form.first_name.label_tag }}<br>
    {{ form.first_name }}
  </div><br>
  <div class="fieldWrapper">
    {{ form.last_name.label_tag }}<br>
    {{ form.last_name }}
  </div><br>
  <div class="fieldWrapper">
    {{ form.username.label_tag }}<br>
    {{ form.username }}
  </div><br>
  <div class="fieldWrapper">
    {{ form.email.label_tag }}<br>
    {{ form.email }}
  </div><br>
  <div class="fieldWrapper">
    {{ form.password1.label_tag }}<br>
    {{ form.password1 }}
  </div><br>
  <div class="fieldWrapper">
    {{ form.password2.label_tag }}<br>
    {{ form.password2 }}
  </div><br>
  <input type="submit" class="btn btn-primary" value="Create Account">
  <p>Already have an account? Login <a href="{% url 'base:login' %}">Here</a></p>

  <div>
    {% if messages %}
      {% for message in messages %}
        <h5>{{ message }}</h5>
      {% endfor %}
    {% endif %}
  </div>
</form>
</div>
{% endblock %}

base/templates/base/home.html
{% extends 'base_template.html' %}
{% block content %}
<div class="m-2">
<h2>Teachers</h2>
<div class="row">
  {% for teacher in teachers %}
  <div class="col-sm">
    <div class="card col-sm m-2 p-2" style="width: 18rem;">
      <img class="card-img-top" style="height: 300px;" src="{{ teacher.teacherImage.url }}" alt="{{ teacher.teacherName.last_name}}">
      <h5 class="card-title">{{ teacher.teacherName.last_name }} {{ teacher.teacherName.first_name }}</h5> 
      <p>{{ teacher.currentSchool }}</p>
      <p class="card-text">
        {% for subject in teacher.subjects.all %}
          {{ subject.subjectName }}, 
          {% endfor %}
          <br>
        </p>
        <h6 class="card-title">{{ teacher.teacherFee }}</h6>
        <a class="btn btn-primary" href="{% url 'base:teacherDetail' teacher.id %}">View More</a>
    </div>
  </div>
  {% endfor %}
</div>
<hr>
<h2>Subjects</h2>
<div class="row">
  {% for subject in subjects %}
  <div class="col-sm">
    <div class="card col-sm m-2 p-2" style="width: 18rem;">
      <img class="card-img-top" style="height: 250px;" src="{{ subject.subjectImage.url }}" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">{{ subject.subjectName }}</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="{% url 'base:viewSubjectTeachers' subject.id %}" class="btn btn-primary">View Teachers</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<hr>
<h2>What Our Customers Say?</h2>
<div class="row">
  {% for testimonial in testimonials %}
    <div class="col-sm card" style="margin: 10px; padding: 10px; border-radius: 10px;">
      <div>
        <p>{{ testimonial.message }}</p>
      </div>
      <p>{{ testimonial.author.first_name }}  
        {% if testimonial.role == 'student' %}
        | Student
        {% elif testimonial.role == 'teacher'  %}
        | Teacher
        {% else %}
        User
        {% endif %}
      </p>
    </div>
  </div>
  {% endfor %}
</div>

{% if request.user.is_authenticated %}
<div class="row">
  <div class='col-sm'>
    <a href="{% url 'base:addTestimonial' %}" style="width: 30%; border-radius: 5px;" class="btn btn-primary">Feedback</a>
  </div>
</div>
{% endif %}
</div>
{% endblock %}

base/templates/base/login_user.html
{% extends 'base_template.html' %}
{% block content %}
<div class="container" style="height: 80vh">
<div class="container m-3 p-3 mx-auto w-50" style="border: 1px solid #ccc;">
<h1>Login</h1>
<form action="" method="post">
  {% csrf_token %}
  <input type="text" name="username" placeholder="Username"><br><br>
  <input type="password" name="password"><br><br>
  <input type="submit" class="btn btn-primary" value="Login">
  <p>Don't have an account? SignUp <a href="{% url 'base:register' %}">Here</a></p>
  <div>
    {% if messages %}
      {% for message in messages %}
        <h5>{{ message }}</h5>
      {% endfor %}
    {% endif %}
  </div>
</form>
</div>
</div>
{% endblock %}

base/templates/base/not_student.html
{% extends 'base_template.html' %}
{% block content %}
<h2>Sorry, You are not a registered student</h2>
<p><a href="{% url 'base:index' %}">Back</a></p>
{% endblock %}

base/templates/base/student_page.html
{% extends 'base_template.html' %}
{% block content %}
<div class="container">
{% if request.user.is_authenticated %}
  <p>Logged in as: {{ request.user.last_name }}</p>
{% endif %}
<h2>Students Using the site</h2>
<hr>
{% if students %}
<div class="row">
{% for student in students %}
<div class="col-sm">
  <div class="card p-3 m-3 rounded-1" style="width: 300px; height: 350px;">
    <img class="card-img-top" style="width: 200px; height: 200px; border-radius: 50%;" src="{{ student.studentImage.url }}" alt="Card image cap">
    <div>
      <p>{{ student.studentName.last_name }} {{ student.studentName.first_name }}</p>
      <p>{{ student.currentSchool }} | {{ student.currentClass }}</p>
      <p>
        {% for subject in student.subjects.all %}
        {{ subject.subjectName }},
        {% endfor %}
      </p>
    </div>
  </div>
</div>
  {% endfor %}
</div>
{% else %}
<p>There are no students yet</p>
{% endif %}
<hr>
<div class="row m-3 p-3">
  <div class="col-sm">
    <a href="{% url 'base:index' %}" class="btn btn-primary rounded-1">Back</a>
  </div>
  <div class="col-sm">
  {% if not isRegistered %} 
   <a href="{% url 'base:postStudent' %}" class="btn btn-primary rounded-1">Register as Student</a>
  {% endif %}
  </div>
</div>
</div>
{% endblock %}

base/templates/base/teacher_detail.html
{% extends 'base_template.html' %}
{% block content %}
<div style="border: 1px #ccc solid" class="container m-3 p-3 mx-auto w-50 rounded-1" >
  <img class="card-img-top" style="border-radius: 50%; height: 300px; width: 300px" src="{{ teacher.teacherImage.url }}" alt="Card image cap">
<h1>{{ teacher.teacherName.last_name }} {{ teacher.teacherName.first_name }}</h1>
<div>
  <h4>{{ teacher.currentSchool }}</h3>
  <div class="container m-2 p-2">
    {{ teacher.teacherDescription}}
  </div>
  <div>
    <h5>
    {% for subject in teacher.subjects.all %}
      {{ subject.subjectName }},
    {% endfor %}
    </h5>
  </div>
  <p>{{ teacher.teacherName.email }}</p>
</div>
<form action="{% url 'base:confirmEnrolment' %}" method="get">
  <input type="hidden" name='teacherId' value="{{ teacher.id }}">
  <div class="row">
    <div class="col-sm">
      <input type="submit" class="btn btn-primary rounded-1" value="Enrol">
    </div>
    <div class="col-sm">
      <a href="{% url 'base:teacherPage' %}" class="btn btn-primary rounded-1">Back</a>
    </div>
  </div>
</form>
</div>
{% endblock %}

base/templates/base/teacher_page.html
{% extends 'base_template.html' %}
{% block content %}
<div class="container" style="">
<p><h2>Teachers on the site</h2></p>
<hr>
<div class="row">
  {% for teacher in teachers %}
  <div class='col-sm'>
    <div class="card m-2 p-2" style="width: 18rem;">
      <img class="card-img-top" style="height: 300px;" src="{{ teacher.teacherImage.url }}" alt="{{ teacher.teacherName.last_name}}">
      <h5 class="card-title">{{ teacher.teacherName.last_name }} {{ teacher.teacherName.first_name }}</h5> {{ teacher.currentSchool }}</p>
      <p class="card-text">
        {% for subject in teacher.subjects.all %}
          {{ subject.subjectName }},
          {% endfor %}
          <br>
        </p>
        <h6 class="card-title">{{ teacher.teacherFee }}</h6>
        <div class="row">
          <div class="col-sm">
            <a class="btn btn-primary rounded-1" href="{% url 'base:teacherDetail' teacher.id %}">View More</a>
          </div>
          {% if request.user.id == teacher.teacherName.id %}
          <div class="col-sm">
            <a class="btn btn-primary rounded-1" href="{% url 'base:teacherProfile' teacher.id %}">My Profile</a>
          </div>
          {% endif %}

        </div>
    </div>
  </div>
  {% endfor %}
</div>
<hr>
<div class="row" style="margin: 10px;">
{% if not isRegistered and not isStudent %}
<a href="{% url 'base:postTeacher' %}" style="width: 50%; margin: auto; border-radius: 5px;" class="btn btn-primary">Register As Teacher</a>
{% endif %}
</div>
<div class="row" style="margin: 10px;">
<a href="{% url 'base:index' %}" style="width: 50%; margin: auto; border-radius: 5px;" class="btn btn-primary">Back</a>
</div>
</div>
{% endblock %}

base/templates/base/teacher_profile.html
{% extends 'base_template.html' %}
{% block content %}
<div class="container" style="height: 80vh">
<h1>Welcome {{ teacher.teacherName.last_name }}</h1>
<div>
  <div class="container">
    <h3>Your Students</h3>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Name</th>
          <th scope="col">School</th>
          <th scope="col">Subjects of Interest</th>
        </tr>
      </thead>
      <tbody>
        {% for student in students %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ student.student.studentName.last_name }} {{ student.student.studentName.first_name }}</td>
          <td>{{ student.student.currentSchool }}</td>
          <td>
            {% for subject in student.subjects.all %}
              {{ subject }},
            {% endfor %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<div class="row p-3 m-3">
<div class="col-sm">
  <a href="{% url 'base:teacherPage' %}" class="btn btn-primary rounded-1">Back</a>
</div>
</div>
</div>
{% endblock %}

base/templates/base/testimonial_create.html
{% extends 'base_template.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Add Testimonial</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form | crispy}}
  <input type="submit" value="Add Testimonial">
</form>
{% endblock %}

base/templates/base/unauthorised_user.html
{% extends 'base_template.html' %}
{% block content %}
<h2>You are not registered student</h2>
<p><a href="{% url 'base:postStudent' %}">Register as Student</a></p>
{% endblock %}

base/templates/base/user_created_success.html
{% extends 'base_template.html' %}
{% block 'content' %}
<h1>User Successfully Created</h1>
<p>I have to make this work</p>
{% endblock %}

base/templates/base/view_subject_teachers.html
{% extends 'base_template.html' %}
{% block content %}
<div class="container">
  <h2>Teacher of {{ subject }}</h2>
  <div class="row">
    {% for teacher in teachers %}
    <div class="col-sm">
      <div class="card col-sm m-2 p-2" style="width: 18rem;">
        <img class="card-img-top" style="height: 300px;" src="{{ teacher.teacher.teacherImage.url }}" alt="{{ teacher.teacherName.last_name}}">
            <h5 class="card-title">{{ teacher.teacher.teacherName.last_name }} {{ teacher.teacher.teacherName.first_name }}</h5> 
            <p>{{ teacher.teacher.currentSchool }}</p>
            <p class="card-text">
              {% for subject in teacher.teacher.subjects.all %}
                {{ subject.subjectName }}, 
                {% endfor %}
                <br>
              </p>
        <h6 class="card-title">{{ teacher.teacher.teacherFee }}</h6>
        <a class="btn btn-primary" href="{% url 'base:teacherDetail' teacher.teacher.id %}">View More</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}